In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("app_00.csv")
df.head()

,id,platform,external_id,title,slug,url,contest_id,problem_index,category,difficulty_raw,tags_raw,stats_raw,metadata_raw,first_seen_at,last_seen_at,last_fetched_at
0,1,CODEFORCES,2269:B,KiaKio and Squared Numbers,NaN,https://codeforces.com/problemset/problem/2269/B,2269,B,NaN,{'rating': 1000},"['brute force', 'implementation']",{'solved_count': 10422},"{'points': 1000.0, 'problemset_name': None}",2026-10-03 10:20:28.863393,2026-10-03 10:38:49.506973,2026-10-03 10:38:49.506973
1,2,CODEFORCES,2269:A,SauSaGe Bank,NaN,https://codeforces.com/problemset/problem/2269/A,2269,A,NaN,{'rating': 800},"['greedy', 'math']",{'solved_count': 15236},"{'points': 500.0, 'problemset_name': None}",2026-10-03 10:20:28.867326,2026-10-03 10:38:49.513474,2026-10-03 10:38:49.513474
2,3,CODEFORCES,2268:F,Deglado,NaN,https://codeforces.com/problemset/problem/2268/F,2268,F,NaN,{'rating': 3500},['constructive algorithms'],{'solved_count': 140},"{'points': 3250.0, 'problemset_name': None}",2026-10-03 10:20:28.869021,2026-10-03 10:38:49.515319,2026-10-03 10:38:49.515319
3,4,CODEFORCES,2268:E,Kia Kio and Tree of Life,NaN,https://codeforces.com/problemset/problem/2268/E,2268,E,NaN,{'rating': 2700},"['data structures', 'fft', 'math', 'trees']",{'solved_count': 287},"{'points': 2750.0, 'problemset_name': None}",2026-10-03 10:20:28.869665,2026-10-03 10:38:49.515939,2026-10-03 10:38:49.515939
4,5,CODEFORCES,2268:D,AghaBalaSar and Hamed,NaN,https://codeforces.com/problemset/problem/2268/D,2268,D,NaN,{'rating': 2600},"['data structures', 'dp', 'trees']",{'solved_count': 524},"{'points': 2250.0, 'problemset_name': None}",2026-10-03 10:20:28.870136,2026-10-03 10:38:49.516646,2026-10-03 10:38:49.516646

In [4]:
df = df[df["platform"] == "CODEFORCES"]
df.head()

,id,platform,external_id,title,slug,url,contest_id,problem_index,category,difficulty_raw,tags_raw,stats_raw,metadata_raw,first_seen_at,last_seen_at,last_fetched_at
0,1,CODEFORCES,2269:B,KiaKio and Squared Numbers,NaN,https://codeforces.com/problemset/problem/2269/B,2269,B,NaN,{'rating': 1000},"['brute force', 'implementation']",{'solved_count': 10422},"{'points': 1000.0, 'problemset_name': None}",2026-10-03 10:20:28.863393,2026-10-03 10:38:49.506973,2026-10-03 10:38:49.506973
1,2,CODEFORCES,2269:A,SauSaGe Bank,NaN,https://codeforces.com/problemset/problem/2269/A,2269,A,NaN,{'rating': 800},"['greedy', 'math']",{'solved_count': 15236},"{'points': 500.0, 'problemset_name': None}",2026-10-03 10:20:28.867326,2026-10-03 10:38:49.513474,2026-10-03 10:38:49.513474
2,3,CODEFORCES,2268:F,Deglado,NaN,https://codeforces.com/problemset/problem/2268/F,2268,F,NaN,{'rating': 3500},['constructive algorithms'],{'solved_count': 140},"{'points': 3250.0, 'problemset_name': None}",2026-10-03 10:20:28.869021,2026-10-03 10:38:49.515319,2026-10-03 10:38:49.515319
3,4,CODEFORCES,2268:E,Kia Kio and Tree of Life,NaN,https://codeforces.com/problemset/problem/2268/E,2268,E,NaN,{'rating': 2700},"['data structures', 'fft', 'math', 'trees']",{'solved_count': 287},"{'points': 2750.0, 'problemset_name': None}",2026-10-03 10:20:28.869665,2026-10-03 10:38:49.515939,2026-10-03 10:38:49.515939
4,5,CODEFORCES,2268:D,AghaBalaSar and Hamed,NaN,https://codeforces.com/problemset/problem/2268/D,2268,D,NaN,{'rating': 2600},"['data structures', 'dp', 'trees']",{'solved_count': 524},"{'points': 2250.0, 'problemset_name': None}",2026-10-03 10:20:28.870136,2026-10-03 10:38:49.516646,2026-10-03 10:38:49.516646

In [8]:
df.count()

id                 11425
platform           11425
external_id        11425
title              11425
slug                   0
url                11425
contest_id         11425
problem_index      11425
category               0
difficulty_raw     11152
tags_raw           11425
stats_raw          11425
metadata_raw       11425
first_seen_at      11425
last_seen_at       11425
last_fetched_at    11425
dtype: int64

In [7]:
df["id"].count()

np.int64(11425)

In [9]:
df = df.drop(columns=["slug", "category"])
df.head()

,id,platform,external_id,title,url,contest_id,problem_index,difficulty_raw,tags_raw,stats_raw,metadata_raw,first_seen_at,last_seen_at,last_fetched_at
0,1,CODEFORCES,2269:B,KiaKio and Squared Numbers,https://codeforces.com/problemset/problem/2269/B,2269,B,{'rating': 1000},"['brute force', 'implementation']",{'solved_count': 10422},"{'points': 1000.0, 'problemset_name': None}",2026-10-03 10:20:28.863393,2026-10-03 10:38:49.506973,2026-10-03 10:38:49.506973
1,2,CODEFORCES,2269:A,SauSaGe Bank,https://codeforces.com/problemset/problem/2269/A,2269,A,{'rating': 800},"['greedy', 'math']",{'solved_count': 15236},"{'points': 500.0, 'problemset_name': None}",2026-10-03 10:20:28.867326,2026-10-03 10:38:49.513474,2026-10-03 10:38:49.513474
2,3,CODEFORCES,2268:F,Deglado,https://codeforces.com/problemset/problem/2268/F,2268,F,{'rating': 3500},['constructive algorithms'],{'solved_count': 140},"{'points': 3250.0, 'problemset_name': None}",2026-10-03 10:20:28.869021,2026-10-03 10:38:49.515319,2026-10-03 10:38:49.515319
3,4,CODEFORCES,2268:E,Kia Kio and Tree of Life,https://codeforces.com/problemset/problem/2268/E,2268,E,{'rating': 2700},"['data structures', 'fft', 'math', 'trees']",{'solved_count': 287},"{'points': 2750.0, 'problemset_name': None}",2026-10-03 10:20:28.869665,2026-10-03 10:38:49.515939,2026-10-03 10:38:49.515939
4,5,CODEFORCES,2268:D,AghaBalaSar and Hamed,https://codeforces.com/problemset/problem/2268/D,2268,D,{'rating': 2600},"['data structures', 'dp', 'trees']",{'solved_count': 524},"{'points': 2250.0, 'problemset_name': None}",2026-10-03 10:20:28.870136,2026-10-03 10:38:49.516646,2026-10-03 10:38:49.516646

In [11]:
df.to_csv("data_Codeforces_01.csv")