In [1]:
import torch
import pandas as pd 
import sqlite3
import json
from sklearn.preprocessing import OneHotEncoder

In [2]:
conn = sqlite3.connect("app.db")

In [3]:
tabels = pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table';", conn)
tabels

       name
0      user
1   session
2  problems

In [4]:
df_01 = pd.read_sql_query("SELECT *" \
                          "FROM user", conn)
df_01

,uid,name,email,password,privilege
0,2,master,master@gmail.com,$2b$12$l6mKrT2u8a6mQ4fXp2tHKufCi96F8oa/e6aCM2k...,admin

In [5]:
df_02 = pd.read_sql_query("SELECT *" \
                          "FROM session", conn)
df_02

   sid  uid                                        token
0    1    3  dzeUZOuXiuIBzay5XEL2gd9oKqjWpb3pc3afJyGZPIM

In [6]:
df_03 = pd.read_sql_query("SELECT *" \
                          "FROM problems", conn)
df_03.head()

,id,platform,external_id,title,slug,url,contest_id,problem_index,category,difficulty_raw,tags_raw,stats_raw,metadata_raw,first_seen_at,last_seen_at,last_fetched_at
0,1,CODEFORCES,2269:B,KiaKio and Squared Numbers,None,https://codeforces.com/problemset/problem/2269/B,2269,B,None,"{""rating"": 1000}","[""brute force"", ""implementation""]","{""solved_count"": 10422}","{""points"": 1000.0, ""problemset_name"": null}",2026-10-03 10:20:28.863393,2026-10-03 10:38:49.506973,2026-10-03 10:38:49.506973
1,2,CODEFORCES,2269:A,SauSaGe Bank,None,https://codeforces.com/problemset/problem/2269/A,2269,A,None,"{""rating"": 800}","[""greedy"", ""math""]","{""solved_count"": 15236}","{""points"": 500.0, ""problemset_name"": null}",2026-10-03 10:20:28.867326,2026-10-03 10:38:49.513474,2026-10-03 10:38:49.513474
2,3,CODEFORCES,2268:F,Deglado,None,https://codeforces.com/problemset/problem/2268/F,2268,F,None,"{""rating"": 3500}","[""constructive algorithms""]","{""solved_count"": 140}","{""points"": 3250.0, ""problemset_name"": null}",2026-10-03 10:20:28.869021,2026-10-03 10:38:49.515319,2026-10-03 10:38:49.515319
3,4,CODEFORCES,2268:E,Kia Kio and Tree of Life,None,https://codeforces.com/problemset/problem/2268/E,2268,E,None,"{""rating"": 2700}","[""data structures"", ""fft"", ""math"", ""trees""]","{""solved_count"": 287}","{""points"": 2750.0, ""problemset_name"": null}",2026-10-03 10:20:28.869665,2026-10-03 10:38:49.515939,2026-10-03 10:38:49.515939
4,5,CODEFORCES,2268:D,AghaBalaSar and Hamed,None,https://codeforces.com/problemset/problem/2268/D,2268,D,None,"{""rating"": 2600}","[""data structures"", ""dp"", ""trees""]","{""solved_count"": 524}","{""points"": 2250.0, ""problemset_name"": null}",2026-10-03 10:20:28.870136,2026-10-03 10:38:49.516646,2026-10-03 10:38:49.516646

In [7]:
sum = df_03.groupby("platform").size()
sum

platform
ATCODER        9625
CODEFORCES    11425
CSES            400
LEETCODE       4069
dtype: int64

In [8]:
df_03["difficulty_raw"] = df_03["difficulty_raw"].apply(json.loads)
df_03["tags_raw"] = df_03["tags_raw"].apply(json.loads)
df_03["stats_raw"] = df_03["stats_raw"].apply(json.loads)
df_03["metadata_raw"] = df_03["metadata_raw"].apply(json.loads)

In [9]:
df_03.to_csv("app_00.csv", index=False)

## INDENT 1

In [10]:
df = pd.read_csv("app_00.csv")

In [11]:
df.head()

,id,platform,external_id,title,slug,url,contest_id,problem_index,category,difficulty_raw,tags_raw,stats_raw,metadata_raw,first_seen_at,last_seen_at,last_fetched_at
0,1,CODEFORCES,2269:B,KiaKio and Squared Numbers,NaN,https://codeforces.com/problemset/problem/2269/B,2269,B,NaN,{'rating': 1000},"['brute force', 'implementation']",{'solved_count': 10422},"{'points': 1000.0, 'problemset_name': None}",2026-10-03 10:20:28.863393,2026-10-03 10:38:49.506973,2026-10-03 10:38:49.506973
1,2,CODEFORCES,2269:A,SauSaGe Bank,NaN,https://codeforces.com/problemset/problem/2269/A,2269,A,NaN,{'rating': 800},"['greedy', 'math']",{'solved_count': 15236},"{'points': 500.0, 'problemset_name': None}",2026-10-03 10:20:28.867326,2026-10-03 10:38:49.513474,2026-10-03 10:38:49.513474
2,3,CODEFORCES,2268:F,Deglado,NaN,https://codeforces.com/problemset/problem/2268/F,2268,F,NaN,{'rating': 3500},['constructive algorithms'],{'solved_count': 140},"{'points': 3250.0, 'problemset_name': None}",2026-10-03 10:20:28.869021,2026-10-03 10:38:49.515319,2026-10-03 10:38:49.515319
3,4,CODEFORCES,2268:E,Kia Kio and Tree of Life,NaN,https://codeforces.com/problemset/problem/2268/E,2268,E,NaN,{'rating': 2700},"['data structures', 'fft', 'math', 'trees']",{'solved_count': 287},"{'points': 2750.0, 'problemset_name': None}",2026-10-03 10:20:28.869665,2026-10-03 10:38:49.515939,2026-10-03 10:38:49.515939
4,5,CODEFORCES,2268:D,AghaBalaSar and Hamed,NaN,https://codeforces.com/problemset/problem/2268/D,2268,D,NaN,{'rating': 2600},"['data structures', 'dp', 'trees']",{'solved_count': 524},"{'points': 2250.0, 'problemset_name': None}",2026-10-03 10:20:28.870136,2026-10-03 10:38:49.516646,2026-10-03 10:38:49.516646

In [12]:
df.tail()

,id,platform,external_id,title,slug,url,contest_id,problem_index,category,difficulty_raw,tags_raw,stats_raw,metadata_raw,first_seen_at,last_seen_at,last_fetched_at
25514,25515,LEETCODE,4065,Rearrange Array by Removing Distinct Values,rearrange-array-by-removing-distinct-values,https://leetcode.com/problems/rearrange-array-...,NaN,NaN,NaN,{'label': 'EASY'},"['Array', 'Hash Table', 'Sorting', 'Heap (Prio...",{'acceptance_rate': 0.7474190564292322},"{'leetcode_internal_id': 4429, 'paid_only': Fa...",2026-10-03 10:23:45.177752,2026-10-03 10:39:59.472852,2026-10-03 10:39:59.472852
25515,25516,LEETCODE,4066,Maximum Equal Adjacent Pairs After at Most One...,maximum-equal-adjacent-pairs-after-at-most-one...,https://leetcode.com/problems/maximum-equal-ad...,NaN,NaN,NaN,{'label': 'MEDIUM'},"['Array', 'Hash Table', 'Counting']",{'acceptance_rate': 0.495395384447118},"{'leetcode_internal_id': 4420, 'paid_only': Fa...",2026-10-03 10:23:45.178192,2026-10-03 10:39:59.473364,2026-10-03 10:39:59.473364
25516,25517,LEETCODE,4067,Longest Subarray With Restricted Pair Sums,longest-subarray-with-restricted-pair-sums,https://leetcode.com/problems/longest-subarray...,NaN,NaN,NaN,{'label': 'MEDIUM'},"['Array', 'Hash Table', 'Sliding Window']",{'acceptance_rate': 0.37700883162009563},"{'leetcode_internal_id': 3985, 'paid_only': Fa...",2026-10-03 10:23:45.178621,2026-10-03 10:39:59.473959,2026-10-03 10:39:59.473959
25517,25518,LEETCODE,4068,Maximize Meeting Earnings with Idle Gaps,maximize-meeting-earnings-with-idle-gaps,https://leetcode.com/problems/maximize-meeting...,NaN,NaN,NaN,{'label': 'HARD'},"['Array', 'Binary Search', 'Dynamic Programmin...",{'acceptance_rate': 0.3888114055478072},"{'leetcode_internal_id': 4314, 'paid_only': Fa...",2026-10-03 10:23:45.179088,2026-10-03 10:39:59.474562,2026-10-03 10:39:59.474562
25518,25519,LEETCODE,4069,Best Time to Buy and Sell Stock with Cooldown II,best-time-to-buy-and-sell-stock-with-cooldown-ii,https://leetcode.com/problems/best-time-to-buy...,NaN,NaN,NaN,{'label': 'MEDIUM'},"['Array', 'Dynamic Programming']",{'acceptance_rate': 0.6878306878306879},"{'leetcode_internal_id': 4117, 'paid_only': True}",2026-10-03 10:23:45.179558,2026-10-03 10:39:59.474973,2026-10-03 10:39:59.474973

In [13]:
df = df.drop(columns=["id", "external_id", "url"])

In [14]:
OHE = OneHotEncoder(sparse_output=False, handle_unknown='error')

encoded = OHE.fit_transform(df[["platform"]])

encoded_df = pd.DataFrame(encoded, columns=OHE.get_feature_names_out(["platform"]), index=df.index)

df = pd.concat([df.drop(columns="platform"),encoded_df], axis=1)

In [15]:
df.head()

,title,slug,contest_id,problem_index,category,difficulty_raw,tags_raw,stats_raw,metadata_raw,first_seen_at,last_seen_at,last_fetched_at,platform_ATCODER,platform_CODEFORCES,platform_CSES,platform_LEETCODE
0,KiaKio and Squared Numbers,NaN,2269,B,NaN,{'rating': 1000},"['brute force', 'implementation']",{'solved_count': 10422},"{'points': 1000.0, 'problemset_name': None}",2026-10-03 10:20:28.863393,2026-10-03 10:38:49.506973,2026-10-03 10:38:49.506973,0.0,1.0,0.0,0.0
1,SauSaGe Bank,NaN,2269,A,NaN,{'rating': 800},"['greedy', 'math']",{'solved_count': 15236},"{'points': 500.0, 'problemset_name': None}",2026-10-03 10:20:28.867326,2026-10-03 10:38:49.513474,2026-10-03 10:38:49.513474,0.0,1.0,0.0,0.0
2,Deglado,NaN,2268,F,NaN,{'rating': 3500},['constructive algorithms'],{'solved_count': 140},"{'points': 3250.0, 'problemset_name': None}",2026-10-03 10:20:28.869021,2026-10-03 10:38:49.515319,2026-10-03 10:38:49.515319,0.0,1.0,0.0,0.0
3,Kia Kio and Tree of Life,NaN,2268,E,NaN,{'rating': 2700},"['data structures', 'fft', 'math', 'trees']",{'solved_count': 287},"{'points': 2750.0, 'problemset_name': None}",2026-10-03 10:20:28.869665,2026-10-03 10:38:49.515939,2026-10-03 10:38:49.515939,0.0,1.0,0.0,0.0
4,AghaBalaSar and Hamed,NaN,2268,D,NaN,{'rating': 2600},"['data structures', 'dp', 'trees']",{'solved_count': 524},"{'points': 2250.0, 'problemset_name': None}",2026-10-03 10:20:28.870136,2026-10-03 10:38:49.516646,2026-10-03 10:38:49.516646,0.0,1.0,0.0,0.0

In [16]:
df["title length"] = df["title"].apply(lambda x: len(x))
df = df.drop(columns=["title"])

In [17]:
df.head()

,slug,contest_id,problem_index,category,difficulty_raw,tags_raw,stats_raw,metadata_raw,first_seen_at,last_seen_at,last_fetched_at,platform_ATCODER,platform_CODEFORCES,platform_CSES,platform_LEETCODE,title length
0,NaN,2269,B,NaN,{'rating': 1000},"['brute force', 'implementation']",{'solved_count': 10422},"{'points': 1000.0, 'problemset_name': None}",2026-10-03 10:20:28.863393,2026-10-03 10:38:49.506973,2026-10-03 10:38:49.506973,0.0,1.0,0.0,0.0,26
1,NaN,2269,A,NaN,{'rating': 800},"['greedy', 'math']",{'solved_count': 15236},"{'points': 500.0, 'problemset_name': None}",2026-10-03 10:20:28.867326,2026-10-03 10:38:49.513474,2026-10-03 10:38:49.513474,0.0,1.0,0.0,0.0,12
2,NaN,2268,F,NaN,{'rating': 3500},['constructive algorithms'],{'solved_count': 140},"{'points': 3250.0, 'problemset_name': None}",2026-10-03 10:20:28.869021,2026-10-03 10:38:49.515319,2026-10-03 10:38:49.515319,0.0,1.0,0.0,0.0,7
3,NaN,2268,E,NaN,{'rating': 2700},"['data structures', 'fft', 'math', 'trees']",{'solved_count': 287},"{'points': 2750.0, 'problemset_name': None}",2026-10-03 10:20:28.869665,2026-10-03 10:38:49.515939,2026-10-03 10:38:49.515939,0.0,1.0,0.0,0.0,24
4,NaN,2268,D,NaN,{'rating': 2600},"['data structures', 'dp', 'trees']",{'solved_count': 524},"{'points': 2250.0, 'problemset_name': None}",2026-10-03 10:20:28.870136,2026-10-03 10:38:49.516646,2026-10-03 10:38:49.516646,0.0,1.0,0.0,0.0,21

In [18]:
temp = df.groupby("slug")
temp.size()

slug
01-matrix                          1
1-bit-and-2-bit-characters         1
132-pattern                        1
2-keys-keyboard                    1
24-game                            1
                                  ..
zigzag-conversion                  1
zigzag-grid-traversal-with-skip    1
zigzag-iterator                    1
zigzag-level-sum-of-binary-tree    1
zuma-game                          1
Length: 4069, dtype: int64

In [19]:
df_03.groupby(["platform",'slug']).count()

                                          id  external_id  title  url  \
platform slug
LEETCODE 01-matrix                         1            1      1    1
         1-bit-and-2-bit-characters        1            1      1    1
         132-pattern                       1            1      1    1
         2-keys-keyboard                   1            1      1    1
         24-game                           1            1      1    1
...                                       ..          ...    ...  ...
         zigzag-conversion                 1            1      1    1
         zigzag-grid-traversal-with-skip   1            1      1    1
         zigzag-iterator                   1            1      1    1
         zigzag-level-sum-of-binary-tree   1            1      1    1
         zuma-game                         1            1      1    1

                                          contest_id  problem_index  category  \
platform slug
LEETCODE 01-matrix                                 0              0         0
         1-bit-and-2-bit-characters                0              0         0
         132-pattern                               0              0         0
         2-keys-keyboard                           0              0         0
         24-game                                   0              0         0
...                                              ...            ...       ...
         zigzag-conversion                         0              0         0
         zigzag-grid-traversal-with-skip           0              0         0
         zigzag-iterator                           0              0         0
         zigzag-level-sum-of-binary-tree           0              0         0
         zuma-game                                 0              0         0

                                          difficulty_raw  tags_raw  stats_raw  \
platform slug
LEETCODE 01-matrix                                     1         1          1
         1-bit-and-2-bit-characters                    1         1          1
         132-pattern                                   1         1          1
         2-keys-keyboard                               1         1          1
         24-game                                       1         1          1
...                                                  ...       ...        ...
         zigzag-conversion                             1         1          1
         zigzag-grid-traversal-with-skip               1         1          1
         zigzag-iterator                               1         1          1
         zigzag-level-sum-of-binary-tree               1         1          1
         zuma-game                                     1         1          1

                                          metadata_raw  first_seen_at  \
platform slug
LEETCODE 01-matrix                                   1              1
         1-bit-and-2-bit-characters                  1              1
         132-pattern                                 1              1
         2-keys-keyboard                             1              1
         24-game                                     1              1
...                                                ...            ...
         zigzag-conversion                           1              1
         zigzag-grid-traversal-with-skip             1              1
         zigzag-iterator                             1              1
         zigzag-level-sum-of-binary-tree             1              1
         zuma-game                                   1              1

                                          last_seen_at  last_fetched_at
platform slug
LEETCODE 01-matrix                                   1                1
         1-bit-and-2-bit-characters                  1                1
         132-pattern                                 1                1
         2-keys-keyboard                             1                1
         24-game                                     1                1
...                                                ...              ...
         zigzag-conversion                           1                1
         zigzag-grid-traversal-with-skip             1                1
         zigzag-iterator                             1                1
         zigzag-level-sum-of-binary-tree             1                1
         zuma-game                                   1                1

[4069 rows x 14 columns]

In [20]:
df = df.drop(columns=["slug"])

In [21]:
temp = df.groupby("problem_index").size()
temp.to_csv("check_00.csv")

In [22]:
df.groupby("contest_id").size()

contest_id
1                          3
10                         5
100                       10
1000                       7
1001                       9
                          ..
yahoo-procon2019-final     5
yahoo-procon2019-qual      6
yuha-c83                   5
yuha-c88                  10
zone2021                   6
Length: 4267, dtype: int64

In [23]:
temp = df.groupby("contest_id").size()
temp.to_csv("check_01.csv")

In [24]:
df["contest_id"].unique()

array(['2269', '2268', '2267', ..., 'yuha-c88', 'zone2021', nan],
      shape=(4268,), dtype=object)

In [25]:
df["problem_index"].unique()

array(['B', 'A', 'F', 'E', 'D', 'C', 'G', 'F2', 'F1', 'H', 'E2', 'E1',
       'A2', 'A1', 'B2', 'B1', 'C2', 'C1', 'D2', 'D1', 'I2', 'I1', 'I',
       'J', 'H3', 'H2', 'H1', 'M', 'L', 'K', 'G1', 'N', 'C3', 'G2', 'E3',
       'F3', 'G3', 'D3', 'B3', 'A3', 'O', 'D5', 'D4', 'A7', 'A6', 'A5',
       'A4', 'D6', 'U3', 'U2', 'U1', 'B4', '14', '13', '12', '11', '10',
       '09', '08', '07', '06', '05', '04', '03', '02', '01', 'M3', 'M2',
       'M1', 'J3', 'J2', 'J1', 'R', 'Q', 'P', 'D9', 'D8', 'D7', 'D10',
       'AP1', 'AP2', 'EX13', 'EX12', 'EX11', 'EX10', 'EX9', 'EX8', 'EX7',
       'EX6', 'EX5', 'EX4', 'EX3', 'EX2', 'EX1', 'AA', 'AB', 'AC', 'AD',
       'AE', 'AF', 'AG', 'AH', 'AI', 'AJ', 'AP3', 'AP4', 'EX26', 'EX25',
       'EX24', 'EX23', 'EX22', 'EX21', 'EX20', 'EX19', 'EX18', 'EX17',
       'EX16', 'EX15', 'EX14', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z',
       'Ex', 'A-Final', '1', '2', '3', '4', '5', 'anagram', 'building',
       'circuit', 'factorial', 'fermat', 'fiber', 'lines', 'mall',
       'packing1', 'packing2', 'packing3', 'packing4', 'packing5',
       'route', 'salt', 'score', 'belt', 'cheating', 'committee',
       'election1', 'election2', 'election3', 'election4', 'election5',
       'flu', 'fraction', 'nightman', 'nile', 'origami', 'ruins', 'sheet',
       'typhoon', 'abduction', 'advertisement', 'chopsticks', 'contest',
       'distribution', 'logo', 'pyramid', 'sequence', 'ski', 'stamps',
       'starry_sky', 'territory', 'aplusb', 'dna', 'finals', 'hideseek',
       'highway', 'lake', 'plugs', 'poster', 'regions', 'sengoku',
       'simroad1', 'simroad2', 'simroad3', 'simroad4', 'simroad5',
       'stairs', 'apples', 'banner', 'bookshelf', 'deciphering', 'dragon',
       'guess', 'ioi', 'joitter', 'keycards', 'orienteering', 'report',
       'shiritori', 'ufo1', 'ufo2', 'ufo3', 'ufo4', 'ufo5',
       'broadcasting1', 'broadcasting2', 'broadcasting3', 'broadcasting4',
       'broadcasting5', 'building2', 'chinese', 'constellation',
       'copypaste', 'fish', 'fortune_telling', 'invitation', 'joi_flag',
       'kangaroo', 'rotate', 'sokoban', 'K1', 'K2', 'K3', 'K4', 'K5',
       'K6', '001', '027', '029', '031', '032', '033', '034', '035',
       '037', '038', '039', '040', '041', '043', '044', '047', '049',
       '050', '051', '053', '054', '055', '056', '057', '058', '059',
       '060', '002', '061', '063', '064', '066', '068', '071', '073',
       '074', '075', '077', '078', '080', '081', '082', '085', '086',
       '087', '091', '092', '097', '098', '100', '103', '104', '089',
       '003', '004', '005', '006', '007', '008', '009', '010', '011',
       '012', '013', '014', '015', '016', '017', '018', '019', '020',
       '021', '022', '023', '024', '025', '026', 'A01', 'A28', 'A30',
       'A31', 'A32', 'A33', 'A34', 'A35', 'A36', 'A37', 'A38', 'A40',
       'A41', 'A42', 'A43', 'A44', 'A45', 'A46', 'A49', 'A51', 'A52',
       'A02', 'A53', 'A54', 'A55', 'A56', 'A57', 'A58', 'A59', 'A60',
       'A61', 'A64', 'A65', 'A66', 'A67', 'A68', 'A69', 'A70', 'A71',
       'A72', 'A73', 'A74', 'A75', 'A76', 'B01', 'A03', 'B02', 'B03',
       'B04', 'B06', 'B08', 'B09', 'B11', 'B12', 'B13', 'B14', 'B17',
       'B18', 'B19', 'B20', 'B21', 'B23', 'B24', 'B26', 'B27', 'A04',
       'B29', 'B30', 'B31', 'B32', 'B33', 'B34', 'B36', 'B37', 'B38',
       'B39', 'B40', 'B41', 'B42', 'B43', 'B44', 'B45', 'B51', 'B52',
       'A05', 'B54', 'B55', 'B56', 'B57', 'B58', 'B59', 'B61', 'B62',
       'B64', 'B65', 'B66', 'B67', 'B68', 'B69', 'C01', 'C02', 'C03',
       'C04', 'C05', 'C06', 'C07', 'C08', 'C10', 'C11', 'C12', 'C13',
       'C14', 'C15', 'C16', 'C17', 'C19', 'C20', 'A07', 'A08', 'A09',
       'A10', 'A11', 'A12', 'A13', 'A14', 'A15', 'A16', 'A17', 'A18',
       'A19', 'A20', 'A21', 'A22', 'A23', 'A24', 'A25', 'A26', '028',
       '030', '036', '042', '045', '046', '048', '052', '062', '065',
       '067', '069', '070', '072', '076', '079', '083', '084', '088',
       '090', nan], dtype=object)

In [26]:
df["contest_id"].dtype

dtype('O')

In [27]:
df["problem_index"].dtype

dtype('O')

In [28]:
temp = df["problem_index"].astype("string")

df["problem_index_letters"] = temp.str.extract(r"([A-Za-z]+)", expand=False)

df["problem_index_numbers"] = pd.to_numeric(temp.str.extract(r"(\d+)", expand=False), errors="coerce")

In [29]:
df.head()

,contest_id,problem_index,category,difficulty_raw,tags_raw,stats_raw,metadata_raw,first_seen_at,last_seen_at,last_fetched_at,platform_ATCODER,platform_CODEFORCES,platform_CSES,platform_LEETCODE,title length,problem_index_letters,problem_index_numbers
0,2269,B,NaN,{'rating': 1000},"['brute force', 'implementation']",{'solved_count': 10422},"{'points': 1000.0, 'problemset_name': None}",2026-10-03 10:20:28.863393,2026-10-03 10:38:49.506973,2026-10-03 10:38:49.506973,0.0,1.0,0.0,0.0,26,B,<NA>
1,2269,A,NaN,{'rating': 800},"['greedy', 'math']",{'solved_count': 15236},"{'points': 500.0, 'problemset_name': None}",2026-10-03 10:20:28.867326,2026-10-03 10:38:49.513474,2026-10-03 10:38:49.513474,0.0,1.0,0.0,0.0,12,A,<NA>
2,2268,F,NaN,{'rating': 3500},['constructive algorithms'],{'solved_count': 140},"{'points': 3250.0, 'problemset_name': None}",2026-10-03 10:20:28.869021,2026-10-03 10:38:49.515319,2026-10-03 10:38:49.515319,0.0,1.0,0.0,0.0,7,F,<NA>
3,2268,E,NaN,{'rating': 2700},"['data structures', 'fft', 'math', 'trees']",{'solved_count': 287},"{'points': 2750.0, 'problemset_name': None}",2026-10-03 10:20:28.869665,2026-10-03 10:38:49.515939,2026-10-03 10:38:49.515939,0.0,1.0,0.0,0.0,24,E,<NA>
4,2268,D,NaN,{'rating': 2600},"['data structures', 'dp', 'trees']",{'solved_count': 524},"{'points': 2250.0, 'problemset_name': None}",2026-10-03 10:20:28.870136,2026-10-03 10:38:49.516646,2026-10-03 10:38:49.516646,0.0,1.0,0.0,0.0,21,D,<NA>

In [30]:
df["problem_index_numbers"] = df["problem_index_numbers"].fillna(0)

In [31]:
df["problem_index_numbers"].unique()

<IntegerArray>
[  0,   2,   1,   3,   5,   4,   7,   6,  14,  13,  12,  11,  10,   9,   8,
  26,  25,  24,  23,  22,  21,  20,  19,  18,  17,  16,  15,  27,  29,  31,
  32,  33,  34,  35,  37,  38,  39,  40,  41,  43,  44,  47,  49,  50,  51,
  53,  54,  55,  56,  57,  58,  59,  60,  61,  63,  64,  66,  68,  71,  73,
  74,  75,  77,  78,  80,  81,  82,  85,  86,  87,  91,  92,  97,  98, 100,
 103, 104,  89,  28,  30,  36,  42,  45,  46,  52,  65,  67,  69,  70,  72,
  76,  62,  48,  79,  83,  84,  88,  90]
Length: 98, dtype: Int64

In [32]:
df["problem_index_letters"].unique()

<StringArray>
[            'B',             'A',             'F',             'E',
             'D',             'C',             'G',             'H',
             'I',             'J',
 ...
       'chinese', 'constellation',     'copypaste',          'fish',
       'fortune',    'invitation',           'joi',      'kangaroo',
        'rotate',       'sokoban']
Length: 112, dtype: string

In [33]:
temp = df["problem_index_letters"].sort_values()
temp.to_csv("check_02.csv")

In [34]:
df["problem_index_letters"].isna().sum()

np.int64(4668)

In [35]:
df["problem_index_letters"].fillna("NULL")

0           B
1           A
2           F
3           E
4           D
         ...
25514    NULL
25515    NULL
25516    NULL
25517    NULL
25518    NULL
Name: problem_index_letters, Length: 25519, dtype: string

In [37]:
df = df.drop(columns=["problem_index", "first_seen_at", "last_seen_at", "last_fetched_at"])
df.head()

,contest_id,category,difficulty_raw,tags_raw,stats_raw,metadata_raw,platform_ATCODER,platform_CODEFORCES,platform_CSES,platform_LEETCODE,title length,problem_index_letters,problem_index_numbers
0,2269,NaN,{'rating': 1000},"['brute force', 'implementation']",{'solved_count': 10422},"{'points': 1000.0, 'problemset_name': None}",0.0,1.0,0.0,0.0,26,B,0
1,2269,NaN,{'rating': 800},"['greedy', 'math']",{'solved_count': 15236},"{'points': 500.0, 'problemset_name': None}",0.0,1.0,0.0,0.0,12,A,0
2,2268,NaN,{'rating': 3500},['constructive algorithms'],{'solved_count': 140},"{'points': 3250.0, 'problemset_name': None}",0.0,1.0,0.0,0.0,7,F,0
3,2268,NaN,{'rating': 2700},"['data structures', 'fft', 'math', 'trees']",{'solved_count': 287},"{'points': 2750.0, 'problemset_name': None}",0.0,1.0,0.0,0.0,24,E,0
4,2268,NaN,{'rating': 2600},"['data structures', 'dp', 'trees']",{'solved_count': 524},"{'points': 2250.0, 'problemset_name': None}",0.0,1.0,0.0,0.0,21,D,0