In [1]:
import torch
import pandas as pd 
import sqlite3
import json

In [2]:
conn = sqlite3.connect("app.db")

In [3]:
tabels = pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table';", conn)
tabels

       name
0      user
1   session
2  problems

In [4]:
df_01 = pd.read_sql_query("SELECT *" \
                          "FROM user", conn)
df_01

,uid,name,email,password,privilege
0,2,master,master@gmail.com,$2b$12$l6mKrT2u8a6mQ4fXp2tHKufCi96F8oa/e6aCM2k...,admin

In [5]:
df_02 = pd.read_sql_query("SELECT *" \
                          "FROM session", conn)
df_02

   sid  uid                                        token
0    1    3  dzeUZOuXiuIBzay5XEL2gd9oKqjWpb3pc3afJyGZPIM

In [6]:
df_03 = pd.read_sql_query("SELECT *" \
                          "FROM problems", conn)
df_03.head()

,id,platform,external_id,title,slug,url,contest_id,problem_index,category,difficulty_raw,tags_raw,stats_raw,metadata_raw,first_seen_at,last_seen_at,last_fetched_at
0,1,CODEFORCES,2269:B,KiaKio and Squared Numbers,None,https://codeforces.com/problemset/problem/2269/B,2269,B,None,"{""rating"": 1000}","[""brute force"", ""implementation""]","{""solved_count"": 10422}","{""points"": 1000.0, ""problemset_name"": null}",2026-10-03 10:20:28.863393,2026-10-03 10:38:49.506973,2026-10-03 10:38:49.506973
1,2,CODEFORCES,2269:A,SauSaGe Bank,None,https://codeforces.com/problemset/problem/2269/A,2269,A,None,"{""rating"": 800}","[""greedy"", ""math""]","{""solved_count"": 15236}","{""points"": 500.0, ""problemset_name"": null}",2026-10-03 10:20:28.867326,2026-10-03 10:38:49.513474,2026-10-03 10:38:49.513474
2,3,CODEFORCES,2268:F,Deglado,None,https://codeforces.com/problemset/problem/2268/F,2268,F,None,"{""rating"": 3500}","[""constructive algorithms""]","{""solved_count"": 140}","{""points"": 3250.0, ""problemset_name"": null}",2026-10-03 10:20:28.869021,2026-10-03 10:38:49.515319,2026-10-03 10:38:49.515319
3,4,CODEFORCES,2268:E,Kia Kio and Tree of Life,None,https://codeforces.com/problemset/problem/2268/E,2268,E,None,"{""rating"": 2700}","[""data structures"", ""fft"", ""math"", ""trees""]","{""solved_count"": 287}","{""points"": 2750.0, ""problemset_name"": null}",2026-10-03 10:20:28.869665,2026-10-03 10:38:49.515939,2026-10-03 10:38:49.515939
4,5,CODEFORCES,2268:D,AghaBalaSar and Hamed,None,https://codeforces.com/problemset/problem/2268/D,2268,D,None,"{""rating"": 2600}","[""data structures"", ""dp"", ""trees""]","{""solved_count"": 524}","{""points"": 2250.0, ""problemset_name"": null}",2026-10-03 10:20:28.870136,2026-10-03 10:38:49.516646,2026-10-03 10:38:49.516646

In [7]:
sum = df_03.groupby("platform").size()
sum

platform
ATCODER        9625
CODEFORCES    11425
CSES            400
LEETCODE       4069
dtype: int64

In [8]:
df_03["difficulty_raw"] = df_03["difficulty_raw"].apply(json.loads)
df_03["tags_raw"] = df_03["tags_raw"].apply(json.loads)
df_03["stats_raw"] = df_03["stats_raw"].apply(json.loads)
df_03["metadata_raw"] = df_03["metadata_raw"].apply(json.loads)

In [9]:
df_03.to_csv("app_00.csv", index=False)

## INDENT 1

In [10]:
df = pd.read_csv("app_00.csv")

In [11]:
df.head()

,id,platform,external_id,title,slug,url,contest_id,problem_index,category,difficulty_raw,tags_raw,stats_raw,metadata_raw,first_seen_at,last_seen_at,last_fetched_at
0,1,CODEFORCES,2269:B,KiaKio and Squared Numbers,NaN,https://codeforces.com/problemset/problem/2269/B,2269,B,NaN,{'rating': 1000},"['brute force', 'implementation']",{'solved_count': 10422},"{'points': 1000.0, 'problemset_name': None}",2026-10-03 10:20:28.863393,2026-10-03 10:38:49.506973,2026-10-03 10:38:49.506973
1,2,CODEFORCES,2269:A,SauSaGe Bank,NaN,https://codeforces.com/problemset/problem/2269/A,2269,A,NaN,{'rating': 800},"['greedy', 'math']",{'solved_count': 15236},"{'points': 500.0, 'problemset_name': None}",2026-10-03 10:20:28.867326,2026-10-03 10:38:49.513474,2026-10-03 10:38:49.513474
2,3,CODEFORCES,2268:F,Deglado,NaN,https://codeforces.com/problemset/problem/2268/F,2268,F,NaN,{'rating': 3500},['constructive algorithms'],{'solved_count': 140},"{'points': 3250.0, 'problemset_name': None}",2026-10-03 10:20:28.869021,2026-10-03 10:38:49.515319,2026-10-03 10:38:49.515319
3,4,CODEFORCES,2268:E,Kia Kio and Tree of Life,NaN,https://codeforces.com/problemset/problem/2268/E,2268,E,NaN,{'rating': 2700},"['data structures', 'fft', 'math', 'trees']",{'solved_count': 287},"{'points': 2750.0, 'problemset_name': None}",2026-10-03 10:20:28.869665,2026-10-03 10:38:49.515939,2026-10-03 10:38:49.515939
4,5,CODEFORCES,2268:D,AghaBalaSar and Hamed,NaN,https://codeforces.com/problemset/problem/2268/D,2268,D,NaN,{'rating': 2600},"['data structures', 'dp', 'trees']",{'solved_count': 524},"{'points': 2250.0, 'problemset_name': None}",2026-10-03 10:20:28.870136,2026-10-03 10:38:49.516646,2026-10-03 10:38:49.516646

In [12]:
df.tail()

,id,platform,external_id,title,slug,url,contest_id,problem_index,category,difficulty_raw,tags_raw,stats_raw,metadata_raw,first_seen_at,last_seen_at,last_fetched_at
25514,25515,LEETCODE,4065,Rearrange Array by Removing Distinct Values,rearrange-array-by-removing-distinct-values,https://leetcode.com/problems/rearrange-array-...,NaN,NaN,NaN,{'label': 'EASY'},"['Array', 'Hash Table', 'Sorting', 'Heap (Prio...",{'acceptance_rate': 0.7474190564292322},"{'leetcode_internal_id': 4429, 'paid_only': Fa...",2026-10-03 10:23:45.177752,2026-10-03 10:39:59.472852,2026-10-03 10:39:59.472852
25515,25516,LEETCODE,4066,Maximum Equal Adjacent Pairs After at Most One...,maximum-equal-adjacent-pairs-after-at-most-one...,https://leetcode.com/problems/maximum-equal-ad...,NaN,NaN,NaN,{'label': 'MEDIUM'},"['Array', 'Hash Table', 'Counting']",{'acceptance_rate': 0.495395384447118},"{'leetcode_internal_id': 4420, 'paid_only': Fa...",2026-10-03 10:23:45.178192,2026-10-03 10:39:59.473364,2026-10-03 10:39:59.473364
25516,25517,LEETCODE,4067,Longest Subarray With Restricted Pair Sums,longest-subarray-with-restricted-pair-sums,https://leetcode.com/problems/longest-subarray...,NaN,NaN,NaN,{'label': 'MEDIUM'},"['Array', 'Hash Table', 'Sliding Window']",{'acceptance_rate': 0.37700883162009563},"{'leetcode_internal_id': 3985, 'paid_only': Fa...",2026-10-03 10:23:45.178621,2026-10-03 10:39:59.473959,2026-10-03 10:39:59.473959
25517,25518,LEETCODE,4068,Maximize Meeting Earnings with Idle Gaps,maximize-meeting-earnings-with-idle-gaps,https://leetcode.com/problems/maximize-meeting...,NaN,NaN,NaN,{'label': 'HARD'},"['Array', 'Binary Search', 'Dynamic Programmin...",{'acceptance_rate': 0.3888114055478072},"{'leetcode_internal_id': 4314, 'paid_only': Fa...",2026-10-03 10:23:45.179088,2026-10-03 10:39:59.474562,2026-10-03 10:39:59.474562
25518,25519,LEETCODE,4069,Best Time to Buy and Sell Stock with Cooldown II,best-time-to-buy-and-sell-stock-with-cooldown-ii,https://leetcode.com/problems/best-time-to-buy...,NaN,NaN,NaN,{'label': 'MEDIUM'},"['Array', 'Dynamic Programming']",{'acceptance_rate': 0.6878306878306879},"{'leetcode_internal_id': 4117, 'paid_only': True}",2026-10-03 10:23:45.179558,2026-10-03 10:39:59.474973,2026-10-03 10:39:59.474973

In [16]:
df.drop(columns=["id", "external_id", "url"])

,platform,title,slug,contest_id,problem_index,category,difficulty_raw,tags_raw,stats_raw,metadata_raw,first_seen_at,last_seen_at,last_fetched_at
0,CODEFORCES,KiaKio and Squared Numbers,NaN,2269,B,NaN,{'rating': 1000},"['brute force', 'implementation']",{'solved_count': 10422},"{'points': 1000.0, 'problemset_name': None}",2026-10-03 10:20:28.863393,2026-10-03 10:38:49.506973,2026-10-03 10:38:49.506973
1,CODEFORCES,SauSaGe Bank,NaN,2269,A,NaN,{'rating': 800},"['greedy', 'math']",{'solved_count': 15236},"{'points': 500.0, 'problemset_name': None}",2026-10-03 10:20:28.867326,2026-10-03 10:38:49.513474,2026-10-03 10:38:49.513474
2,CODEFORCES,Deglado,NaN,2268,F,NaN,{'rating': 3500},['constructive algorithms'],{'solved_count': 140},"{'points': 3250.0, 'problemset_name': None}",2026-10-03 10:20:28.869021,2026-10-03 10:38:49.515319,2026-10-03 10:38:49.515319
3,CODEFORCES,Kia Kio and Tree of Life,NaN,2268,E,NaN,{'rating': 2700},"['data structures', 'fft', 'math', 'trees']",{'solved_count': 287},"{'points': 2750.0, 'problemset_name': None}",2026-10-03 10:20:28.869665,2026-10-03 10:38:49.515939,2026-10-03 10:38:49.515939
4,CODEFORCES,AghaBalaSar and Hamed,NaN,2268,D,NaN,{'rating': 2600},"['data structures', 'dp', 'trees']",{'solved_count': 524},"{'points': 2250.0, 'problemset_name': None}",2026-10-03 10:20:28.870136,2026-10-03 10:38:49.516646,2026-10-03 10:38:49.516646
...,...,...,...,...,...,...,...,...,...,...,...,...,...
25514,LEETCODE,Rearrange Array by Removing Distinct Values,rearrange-array-by-removing-distinct-values,NaN,NaN,NaN,{'label': 'EASY'},"['Array', 'Hash Table', 'Sorting', 'Heap (Prio...",{'acceptance_rate': 0.7474190564292322},"{'leetcode_internal_id': 4429, 'paid_only': Fa...",2026-10-03 10:23:45.177752,2026-10-03 10:39:59.472852,2026-10-03 10:39:59.472852
25515,LEETCODE,Maximum Equal Adjacent Pairs After at Most One...,maximum-equal-adjacent-pairs-after-at-most-one...,NaN,NaN,NaN,{'label': 'MEDIUM'},"['Array', 'Hash Table', 'Counting']",{'acceptance_rate': 0.495395384447118},"{'leetcode_internal_id': 4420, 'paid_only': Fa...",2026-10-03 10:23:45.178192,2026-10-03 10:39:59.473364,2026-10-03 10:39:59.473364
25516,LEETCODE,Longest Subarray With Restricted Pair Sums,longest-subarray-with-restricted-pair-sums,NaN,NaN,NaN,{'label': 'MEDIUM'},"['Array', 'Hash Table', 'Sliding Window']",{'acceptance_rate': 0.37700883162009563},"{'leetcode_internal_id': 3985, 'paid_only': Fa...",2026-10-03 10:23:45.178621,2026-10-03 10:39:59.473959,2026-10-03 10:39:59.473959
25517,LEETCODE,Maximize Meeting Earnings with Idle Gaps,maximize-meeting-earnings-with-idle-gaps,NaN,NaN,NaN,{'label': 'HARD'},"['Array', 'Binary Search', 'Dynamic Programmin...",{'acceptance_rate': 0.3888114055478072},"{'leetcode_internal_id': 4314, 'paid_only': Fa...",2026-10-03 10:23:45.179088,2026-10-03 10:39:59.474562,2026-10-03 10:39:59.474562
25518,LEETCODE,Best Time to Buy and Sell Stock with Cooldown II,best-time-to-buy-and-sell-stock-with-cooldown-ii,NaN,NaN,NaN,{'label': 'MEDIUM'},"['Array', 'Dynamic Programming']",{'acceptance_rate': 0.6878306878306879},"{'leetcode_internal_id': 4117, 'paid_only': True}",2026-10-03 10:23:45.179558,2026-10-03 10:39:59.474973,2026-10-03 10:39:59.474973